# Hammad Hassan
PIAIC86267
batch 9

In [2]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
type(x)

numpy.ndarray

In [3]:
x.shape

(2, 3)

In [4]:
x.dtype

dtype('int32')

In [5]:
x[1, 2]

6

In [7]:
y = x[:,1]
y

array([2, 5], dtype=int32)

In [9]:
y[0] = 9
y
x

array([[1, 9, 3],
       [4, 5, 6]], dtype=int32)

In [12]:
list(map(hex, y))

['0x9000000', '0x5000000']

In [11]:
y.byteswap(inplace=True)

array([150994944,  83886080], dtype=int32)

In [21]:
z = x.copy()
z

array([[        1, 150994944,         3],
       [        4,  83886080,         6]], dtype=int32)

In [17]:
z.fill(0)
z

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [19]:
a = np.eye(2)
a

array([[1., 0.],
       [0., 1.]])

In [20]:
b = np.ones((2, 2)) * 2
b

array([[2., 2.],
       [2., 2.]])

In [22]:
a.dot(b)

array([[2., 2.],
       [2., 2.]])

In [23]:
a.dot(b).dot(b)

array([[8., 8.],
       [8., 8.]])

In [24]:
a.flatten()

array([1., 0., 0., 1.])

In [26]:
x.sort(axis=1)
x

array([[        1,         3, 150994944],
       [        4,         6,  83886080]], dtype=int32)

In [27]:
a.sort(axis=0)
x

array([[        1,         3, 150994944],
       [        4,         6,  83886080]], dtype=int32)

In [34]:
x=np.array([[1,2],[3,4]], np.int32)
x

array([[1, 2],
       [3, 4]], dtype=int32)

In [36]:
 x.transpose()

array([[1, 3],
       [2, 4]], dtype=int32)

In [37]:
x = np.sqrt([1+0j, 0+1j])
x.real

array([1.        , 0.70710678])

In [38]:
x = np.sqrt([1+0j, 0+1j])
x.imag

array([0.        , 0.70710678])

In [39]:
x.imag.dtype

dtype('float64')

In [47]:
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
x.flat[3]

4

In [49]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [43]:
x.T.flat[3]

5

In [44]:
type(x.flat)

numpy.flatiter

In [45]:
x.sum(axis=0)

array([5, 7, 9])

In [52]:
x = np.dtype('8f')
x.subdtype

(dtype('float32'), (8,))

In [54]:
x.shape

(8,)

In [55]:
x.flags

0

In [56]:
x.descr

[('', '|V32')]

In [57]:
x.alignment

4

In [58]:
x.base

dtype('float32')