### **Numpy_Assignment_2::**

Question:1 

Convert a 1D array to a 2D array with 2 rows?

Desired output::
array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])



In [6]:
import numpy as np
a = np.arange(0,10).reshape(2,5)
print (a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Question:2

How to stack two arrays vertically?

Desired Output::
array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

In [18]:
import numpy as np
a = np.arange(0,10).reshape(2,5)
b = np.ones(10).reshape(2,5)
c = np.vstack((a,b))
print (c)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Question:3

How to stack two arrays horizontally?

Desired Output::
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [19]:
import numpy as np
a = np.arange(0,10).reshape(2,5)
b = np.ones(10).reshape(2,5)
c = np.hstack((a,b))
print (c)

[[0. 1. 2. 3. 4. 1. 1. 1. 1. 1.]
 [5. 6. 7. 8. 9. 1. 1. 1. 1. 1.]]


Question:4

How to convert an array of arrays into a flat 1d array?

Desired Output::
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
import numpy as np
a = np.array([[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]])
print (a)
b = a.flatten()
print (b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]


Question:5

How to Convert higher dimension into one dimension?

Desired Output::
array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [30]:
import numpy as np
a = np.arange(0,15).reshape(3,5)
print (a)
b = a.flatten()
print (b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


Question:6

Convert one dimension to higher dimension?

Desired Output::
array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11], [12, 13, 14]])

In [34]:
import numpy as np
a = np.arange(0,15)
print (a)
b = np.reshape(a,(5,3))
print (b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


Question:7

Create 5x5 an array and find the square of an array?

In [36]:
import numpy as np
a = np.arange(0,25).reshape(5,5)
print (a)
np.square(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

Question:8

Create 5x6 an array and find the mean?

In [37]:
import numpy as np
a = np.arange(0,30).reshape(5,6)
print (a)
np.mean(a, axis=1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


array([ 2.5,  8.5, 14.5, 20.5, 26.5])

Question:9

Find the standard deviation of the previous array in Q8?

In [38]:
import numpy as np
a = np.arange(0,30).reshape(5,6)
print (a)
np.std(a, axis=1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


array([1.70782513, 1.70782513, 1.70782513, 1.70782513, 1.70782513])

Question:10

Find the median of the previous array in Q8?

In [39]:
import numpy as np
a = np.arange(0,30).reshape(5,6)
print (a)
np.median(a, axis=1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


array([ 2.5,  8.5, 14.5, 20.5, 26.5])

Question:11

Find the transpose of the previous array in Q8?

In [41]:
import numpy as np
a = np.arange(0,30).reshape(5,6)
print (a)
np.transpose(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

Question:12

Create a 4x4 an array and find the sum of diagonal elements?

In [43]:
import numpy as np
a = np.arange(0,16).reshape(4,4)
print (a)
np.trace(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


30

Question:13

Find the determinant of the previous array in Q12?

In [44]:
import numpy as np
a = np.arange(0,16).reshape(4,4)
print (a)
np.linalg.det(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


0.0

Question:14

Find the 5th and 95th percentile of an array?

In [49]:
import numpy as np
a = np.arange(0,16).reshape(4,4)
print (a)
print(np.percentile(a, 5))
print(np.percentile(a, 95))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
0.75
14.25


Question:15

How to find if a given array has any null values?

In [51]:
import numpy as np
np.isnan([np.log(-1.),1.,np.log(0)])
#array([ True, False, False])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([ True, False, False])